version: '3'
services:
  mongodb:
    image: mongo:4
    restart: always
    container_name: ab-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mydb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge

volumes:
  mongodb: